[versions]
agp = "8.6.0"
hcaptchaAndroidSdk = "4.0.2"
junit = "4.13.2"
junitVersion = "1.2.1"
espressoCore = "3.6.1"
appcompat = "1.7.0"
material = "1.12.0"
activity = "1.9.2"
constraintlayout = "2.1.4"
materialVersion = "1.4.0"
recyclerview = "1.3.2"
recyclerviewSelection = "1.1.0"
retrofit = "2.9.0"
sdk = "7.0.2"
volley = "1.2.1"
legacySupportV4 = "1.0.0"
playServicesSafetynet = "18.1.0"

[libraries]
converter-gson = { module = "com.squareup.retrofit2:converter-gson", version.ref = "retrofit" }
hcaptcha-android-sdk = { module = "com.hcaptcha.sdk:hcaptcha-android-sdk", version.ref = "hcaptchaAndroidSdk" }
junit = { group = "junit", name = "junit", version.ref = "junit" }
ext-junit = { group = "androidx.test.ext", name = "junit", version.ref = "junitVersion" }
espresso-core = { group = "androidx.test.espresso", name = "espresso-core", version.ref = "espressoCore" }
appcompat = { group = "androidx.appcompat", name = "appcompat", version.ref = "appcompat" }
material = { group = "com.google.android.material", name = "material", version.ref = "material" }
activity = { group = "androidx.activity", name = "activity", version.ref = "activity" }
constraintlayout = { group = "androidx.constraintlayout", name = "constraintlayout", version.ref = "constraintlayout" }
material-v140 = { module = "com.google.android.material:material", version.ref = "materialVersion" }
recyclerview = { module = "androidx.recyclerview:recyclerview", version.ref = "recyclerview" }
recyclerview-selection = { module = "androidx.recyclerview:recyclerview-selection", version.ref = "recyclerviewSelection" }
retrofit = { module = "com.squareup.retrofit2:retrofit", version.ref = "retrofit" }
sdk = { module = "com.github.hCaptcha.hcaptcha-android-sdk:sdk", version.ref = "sdk" }
volley = { module = "com.android.volley:volley", version.ref = "volley" }
legacy-support-v4 = { group = "androidx.legacy", name = "legacy-support-v4", version.ref = "legacySupportV4" }
play-services-safetynet = { group = "com.google.android.gms", name = "play-services-safetynet", version.ref = "playServicesSafetynet" }

[plugins]
android-application = { id = "com.android.application", version.ref = "agp" }

